version: "3.8"

services:
  publisher:
    build:
      context: ./publisher/
    ports:
      - "3232:3232"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3232
      - RABBITMQ_IP=""
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=""
      - RABBITMQ_PASSWORD=""
    networks:
      - push_network

  consumer:
    build:
      context: ./consumer/
    environment:
      - POLLING_DELAY=5 #seconds
      - ASYNC_TASKS_LIMIT=5
      - RABBITMQ_IP=""
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=""
      - RABBITMQ_PASSWORD=""
      - SENDGRID_KEY=""
      - MAIL_FROM_EMAIL=""
      - MAIL_FROM_NAME="Homelab"
      - MAIL_TO=""
    networks:
      - push_network

networks:
  push_network:
    driver: bridge
